### ISSUE TITLE
Unchecked cast when loading object from file

### ISSUE THREAD

**Issue by gerhean** [nus-cs2103-AY1920S2/forum#10]
When I compile my code, I get the following warning
```
Note: <hidden>\duke\src\main\java\dukebot\Storage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

The offending line is:
`ArrayList<Task> data = (ArrayList<Task>) readStream.readObject();`

Am I allowed to just add:
`@SuppressWarnings("unchecked")`
above?

Or is there a more proper way to avoid the warning, other than breaking down the object manually and saving and writing in string.

**Comment by mario7lorenzo** [comment]
Hi there! May I know what do you want to do with that line? So that I may be able to provide a suggestion to make it more proper. As far as I read your issue, I think you are trying to read an ArrayList object from the file (?). If so, my suggestion is to read the Task instance one by one, and perform the type casting, before adding them to the ArrayList.

----UPDATE----
If you are using the InputStream, this article may be helpful for you:
[https://howtodoinjava.com/java/collections/arraylist/serialize-deserialize-arraylist/](url)
at point 3.1

So basically, you can try using the try and catch block to verify the content of the arraylist.
Here's the snippet of what they do:
```
ArrayList<Employee> employees = new ArrayList<>();
         
        try
        {
            FileInputStream fis = new FileInputStream("employeeData");
            ObjectInputStream ois = new ObjectInputStream(fis);
 
            employees = (ArrayList) ois.readObject();
 
            ois.close();
            fis.close();
        } 
        catch (IOException ioe) 
        {
            ioe.printStackTrace();
            return;
        } 
        catch (ClassNotFoundException c) 
        {
            System.out.println("Class not found");
            c.printStackTrace();
            return;
        }
```

You can try that option, and reply whether it is successful or not.

In my opinion, adding `@SuppressWarnings("unchecked")` is not a good practice. The compiler provides the message for a reason!

**Comment by gerhean** [comment]
I am indeed using InputStream to serialize and deserialize ArrayList.

My current full code is:
```
if (new File(this.storagePath).isFile()) {
            ArrayList<Task> data;
            try{
                FileInputStream readData = new FileInputStream(new File(this.storagePath));
                ObjectInputStream readStream = new ObjectInputStream(readData);

                data = (ArrayList) readStream.readObject();
                readStream.close();

                return data;
            }catch (IOException | ClassNotFoundException e) {
                e.printStackTrace();
            }
        }
```

The compiler displays the warning even though I have already caught the exceptions.

**Comment by gerhean** [comment]
I was able to bypass the warning by storing an Array instead of ArrayList:

```
                Object obj = readStream.readObject();
                if (obj instanceof Task[]) {
                    return new ArrayList<>(Arrays.asList((Task[]) obj));
                }
```

Thanks.
