### ISSUE TITLE
Symbols not printable

### ISSUE THREAD

**Issue by xCelestialPhoenix** [nus-cs2103-AY1920S2/forum#4]
I am printing question marks instead of crosses and ticks in IntelliJ's console and PowerShell. I did not modify anything code from the extension section so I believe it's an encoding issue. Here is the code I use for printing:

In Task class:
```
public String getStatusIcon() {
    return (isDone ? "\u2713" : "\u2718"); //no modifications
}

public String toString() {
        return "[" + getStatusIcon() + "] " + description;
    }
```

In Duke(Main):
```
for (int i = 0; i < taskList.size(); i++) {
    System.out.println((i + 1) + "." + taskList.get(i));
}
```

I'm running IntelliJ community 2019.3 v11.0.4, Java JDK 11 on Windows.

**Comment by okkhoy** [comment]
This is a known issue, though I have forgotten the resolution 😞 

If anyone else managed to find a solution, please do post it here. In the meantime, I will ask someone in the developer team to take a look and respond.

An alternate route:
My suggestion here would be to use a different character instead of the cross and tick (like `Y` and `N`, possibly?) to proceed with the work.

**Comment by nigelnnk** [comment]
IntelliJ accepts the use of the tick and cross symbols directly by copying and pasting the unicode text over. Should not be an issue?

**Comment by xCelestialPhoenix** [comment]
That works, but I feel like it's a little hacky.

**Comment by sharadhr** [comment]
One will have to configure `javac` and `java` as used by IntelliJ to accept UTF-8 symbols. I am using VS Code, however, and haven't encountered this yet. 

That said, in IntelliJ, the following _two_ steps can be done.

1. Set the encoding of the source code files to `UTF-8`: on the bottom-right of the IDE, you might see this:
![image](https://user-images.githubusercontent.com/3754080/72665344-73023b00-3a42-11ea-9bfc-97011ccd5a87.png) 
I've got UTF-8 already selected, but yours might be ANSI or something else. Change it to UTF-8. 

2. Certain options need to be passed to the `javac` compiler and the `java` executable used by IntelliJ to explicitly support compiling and running of UTF-8 files, containing UTF-8 characters.
Go to <kbd>File</kbd>/<kbd>Settings</kbd>/<kbd>Build, Execution and Deployment</kbd>/<kbd>Compiler</kbd>, and under `Additional command line parameters`, type this in: `-encoding utf8`

**Comment by xCelestialPhoenix** [comment]
Mine has been utf-8 all along. I tried (2) but it still did not work. Thanks for the effort though.

**Comment by sharadhr** [comment]
So, I noticed that when running the file, this is the command executed by my installation of IntelliJ:
```
"C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3\jbr\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3\lib\idea_rt.jar=5908:C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3\bin" -Dfile.encoding=UTF-8 -classpath "D:\User Libraries\duke\out\production\duke" Duke
```

Notice the `-Dfile.encoding=UTF-8` there. There has to be a way to change the build options, because this is my (dummy) source:
```
public class Duke {
    public static void main(String[] args) {
        String logo = " ____        _        \n"
                + "|  _ \\ _   _| | _____ \n"
                + "| | | | | | | |/ / _ \\\n"
                + "| |_| | |_| |   <  __/\n"
                + "|____/ \\__,_|_|\\_\\___|\n";
        System.out.println("Hello from\n" + logo);
        System.out.println("\u2713" + " " + "\u2718");
    }
}
```
I see the tick and cross in the output, no problem.
___

EDIT: After some more digging, I found that there exists a file called `./idea/encodings.xml`. The _console_ has its own encoding, too. Intriguing. One can search for 'UTF-8' in the Settings menu, and change the project settings to UTF-8. One can also go to <kbd>Help</kbd>/<kbd>Edit Custom VM Options</kbd> and append these two lines to the end, and see if it works:
```
-Dconsole.encoding=UTF-8
-Dfile.encoding=UTF-8
```

**Comment by xCelestialPhoenix** [comment]
After so long I finally found a solution [here](https://smallbusiness.chron.com/unicode-symbols-not-display-java-39315.html). Instead of using `system.out.println()`, I'm using printstream() which can specify the encoding standard.
